### ISSUE TITLE
Put a link in the Readme to the rationale behind this template

### ISSUE THREAD

**Issue by offray** [kenohori/thesis#1]
Hi Ken,

Thanks again for this template. I have been using it with my PhD thesis and I plan to explore its use on other publications.

I would suggest to link [A 1.5 column layout in LaTeX](https://3d.bk.tudelft.nl/ken/en/2016/04/17/a-1.5-column-layout-in-latex.html) in the readme, because it shows the rationale behind this template and also from that page to this repository to appreciate better the relationship between both.

**Comment by kenohori** [comment]
Hi Offray,

Good idea. I've added links to this blog post and a few other related ones.

Thanks!
